# Global settings
## https://starship.rs/config/
## Get editor completions based on the config schema
"$schema" = '~/.config/starship/config-schema.json'

## Inserts a blank line between shell prompts
add_newline = true

## Timeout for commands executed by starship (in milliseconds)
command_timeout = 5000

# Move the $time to the first line and remove the modules barely used
format = """
$shlvl\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$c\
$cmake\
$golang\
$helm\
$java\
$gradle\
$lua\
$nodejs\
$perl\
$php\
$pulumi\
$python\
$rlang\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vagrant\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$kubernetes\
$env_var\
$custom\
$sudo\
$cmd_duration\
$time\
$line_break\
$jobs\
$battery\
$status\
$os\
$container\
$shell\
$character"""

# Replace the '❯' symbol in the prompt with '➜'
[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Display the current Kubernetes context name and namespace
[kubernetes]
disabled = true
symbol = '⎈ '
format = 'at [$symbol$context/$namespace](cyan) '

# Display the java module with style not dimmed
[java]
style = 'red'

# Display the conda module with style not bold
[conda]
style = 'green'

# Disable the AWS module to not show the current AWS region and profile
[aws]
disabled = true

# Disable the Google Cloud module to not show the current GCP region and profile
[gcloud]
disabled = true

# Disable the OpenStack module to not show the current OpenStack cloud and project
[openstack]
disabled = true

# Show how long the last command took to execute
[cmd_duration]
min_time = 4_000 # Shortest duration to show time for (in milliseconds)

# Show the path to your current directory
[directory]
truncation_symbol = ' .../'
home_symbol = ' ~'
truncation_length = 5 # The number of parent folders that the current directory should be truncated to
truncate_to_repo = false # Whether or not to truncate to the root of the git repo that you're currently in

# Show the current local time
[time]
disabled = false
format = 'at [ $time]($style) '
time_format = '%T'
utc_time_offset = '+8'
style = 'bold black'
