# .bashrc

# Source global definitions
if [[ -f /etc/bashrc ]]; then
  . /etc/bashrc
fi

# Suppress the warning messages of default interactive shell
export BASH_SILENCE_DEPRECATION_WARNING=1

# User specific aliases and functions
alias ls='lsd -N'
alias ll='lsd -N -l --size short --date "+%a %Y-%m-%d_%H:%M:%S"'
alias la='lsd -N -a'
alias lrt='lsd -N -lrth --size short --date "+%a %Y-%m-%d_%H:%M:%S"'
alias lvh='lsd -N -lvh --size short --date "+%a %Y-%m-%d_%H:%M:%S"'
alias tree='lsd -N --tree --group-dirs first'
alias rm='trash-put -i'
alias cp='cp -i'
alias mv='mv -i'
alias grep='grep --color=auto'
alias updatedb='sudo gupdatedb --localpaths=/ --prunepaths="/Library /private /System /Volumes" --output=$HOME/.locatedb'
alias locate='glocate --database=$HOME/.locatedb'
alias tar='gtar'
alias sed='gsed'
alias date='gdate'
alias kctx='kubectx'
alias kns='env -u HTTP_PROXY -u HTTPS_PROXY -u ALL_PROXY kubens'
alias k9s='env -u HTTP_PROXY -u HTTPS_PROXY -u ALL_PROXY k9s'
alias watch='watch '
alias ccat='bat --theme="Solarized (dark)" --style=plain --paging=never'

# LANG
export LANG=en_US.UTF-8

# Log the history commands with time stamps
export HISTFILESIZE="1000000000"
export HISTSIZE="1000000"
export HISTTIMEFORMAT="%Y-%m-%d_%H:%M:%S "
export HISTIGNORE="history*:pwd:ls:ll:la:lrt:lvh:clear:exit:zsh"
export HISTCONTROL="ignoredups"

# To support autojump, append "histor -a" to the end of the existing $PROMPT_COMMAND
export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND ;} history -a"

# Enable auto-completion of bash
source /opt/homebrew/etc/profile.d/bash_completion.sh

# Enable auto-completion via sudo
complete -cf sudo

# Enable auto-completion of aws
complete -cf aws

# Enable color codes and pager for Git commands
export LESS='-R'
export GIT_PAGER='less -R'

# Readline library accepts \001 and \002 as non-visible text delimiters
# The bash-specific \[ and \] are translated to \001 and \002
_nvt_open=$'\001' # non-visible text open
_nvt_close=$'\002' # non-visible text close

# Enable color in terminal with tput and non-visible text delimiters
_tput_black=${_nvt_open}$(tput setaf 0)${_nvt_close}
_tput_red=${_nvt_open}$(tput setaf 1)${_nvt_close}
_tput_green=${_nvt_open}$(tput setaf 2)${_nvt_close}
_tput_yellow=${_nvt_open}$(tput setaf 3)${_nvt_close}
_tput_blue=${_nvt_open}$(tput setaf 4)${_nvt_close}
_tput_magenta=${_nvt_open}$(tput setaf 5)${_nvt_close}
_tput_cyan=${_nvt_open}$(tput setaf 6)${_nvt_close}
_tput_white=${_nvt_open}$(tput setaf 7)${_nvt_close}
_tput_bold=${_nvt_open}$(tput bold)${_nvt_close}
_tput_reset=${_nvt_open}$(tput sgr0)${_nvt_close}

# Check current public IP
function publicip() {
  local website_list=(
    ipinfo.io
    checkip.amazonaws.com
    ifconfig.co
    ifconfig.me
    ifconfig.io
  )

  if [[ -n "$HTTP_PROXY" ]]; then
    echo "${_tput_yellow}NOTICE: HTTP_PROXY has been set${_tput_reset}"
  fi

  local website
  for website in ${website_list[@]}; do
    echo "${website}: $(curl -s ${website})"
  done
}

# Check specific public IP
function checkip() {
  if [[ -n "$HTTP_PROXY" ]]; then
    echo "${_tput_yellow}NOTICE: HTTP_PROXY has been set${_tput_reset}"
  fi

  curl -s ipinfo.io/$1
}

# NVM
function enable_nvm() {
  export NVM_DIR=$HOME/.nvm
  source /opt/homebrew/opt/nvm/nvm.sh
}

# Anaconda
function enable_conda() {
  source /opt/homebrew/anaconda3/etc/profile.d/conda.sh
}

# Filesystem Markers & Jump
export MARKPATH=$HOME/.marks

function jump() {
  cd -P $MARKPATH/$1 2>/dev/null || echo "No such mark: $1"
}

function mark() {
  mkdir -p $MARKPATH; ln -s $(pwd) $MARKPATH/$1
}

function unmark() {
  /bin/rm -i $MARKPATH/$1
}

function _marks() {
  COMPREPLY=()
  local cur=${COMP_WORDS[COMP_CWORD]};
  local com=${COMP_WORDS[COMP_CWORD-1]};
  case $com in
    'jump')
      local marks=($(ls ${MARKPATH}))
      COMPREPLY=($(compgen -W '${marks[@]}' -- $cur))
      ;;
    'unmark')
      local marks=($(ls ${MARKPATH}))
      COMPREPLY=($(compgen -W '${marks[@]}' -- $cur))
      ;;
  esac
}

complete -F _marks jump
complete -F _marks unmark

# Fast way to cd up N directory levels
function up() {
  if [[ ! $1 =~ ^[0-9]+$ ]]; then
    cd ..
  else
    cd "$(printf '../%.0s' $(seq 1 $1))"
  fi
  pwd
}

# Enable auto-completion of smartroutes
function _routes() {
  COMPREPLY=()
  local cur=${COMP_WORDS[COMP_CWORD]};
  local com=${COMP_WORDS[COMP_CWORD-1]};
  case $com in
    'smartroutes')
      local params=(on off status exception)
      COMPREPLY=($(compgen -W '${params[@]}' -- $cur))
      ;;
  esac
}

complete -F _routes smartroutes

# Enable Starship
eval "$(starship init bash)"
export STARSHIP_CONFIG=$HOME/.config/starship/starship.toml

# Show current Kubernetes context and namespace with colors in Starship Bash prompt
function kubeon() {
  sed -i '/\[kubernetes\]/!b;n;s/disabled = true/disabled = false/' $STARSHIP_CONFIG
}

function kubeoff() {
  sed -i '/\[kubernetes\]/!b;n;s/disabled = false/disabled = true/' $STARSHIP_CONFIG
}

# Generate a random password
function pwrgen() {
  if [[ $1 =~ ^[0-9]+$ ]]; then
    local passwdlen=$1
  else
    local passwdlen=16
  fi

  local passwdstr=$(pwgen -cnsB ${passwdlen} 1)
  local randomnum=$((RANDOM % (passwdlen - 2) + 2))
  local passwdout=$(echo ${passwdstr} | sed "s/./_/$randomnum")
  echo "${_tput_yellow}${passwdout}${_tput_reset}"
}

# Enable auto-completion of kubectl
source <(kubectl completion bash)
alias k='env -u HTTP_PROXY -u HTTPS_PROXY -u ALL_PROXY kubectl'
complete -o default -F __start_kubectl k

# The plugin manager for kubectl command-line tool
export PATH=$HOME/.krew/bin:$PATH

# Enable autojump
source /opt/homebrew/etc/profile.d/autojump.sh

# Enable or disable HTTP proxy
declare -A _proxy_protocols=(
  ["HTTP_PROXY"]="http"
  ["HTTPS_PROXY"]="http"
  ["ALL_PROXY"]="socks5"
)

function proxyon() {
  local socket="127.0.0.1:7890"
  local proxy_type
  for proxy_type in "${!_proxy_protocols[@]}"; do
    export ${proxy_type}=${_proxy_protocols[$proxy_type]}://${socket}
  done

  local noproxy_list=(
    "localhost"
    "127.0.0.0/8"
    "10.0.0.0/8"
    "172.16.0.0/12"
    "192.168.0.0/16"
    "0.0.0.0/8"
    "100.64.0.0/10"
    "169.254.0.0/16"
    "198.18.0.0/15"
  )

  export NO_PROXY=$(IFS=,; echo "${noproxy_list[*]}")

  printenv | /usr/bin/grep "_PROXY"
}

function proxyoff() {
  unset ${!_proxy_protocols[@]} NO_PROXY
  echo "unset ${!_proxy_protocols[@]} NO_PROXY"
}

